include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    await_only_futures: true
    unawaited_futures: true
    close_sinks: true
    avoid_positional_boolean_parameters: true
    always_use_package_imports: true
    always_declare_return_types: true
    cancel_subscriptions: true
    sized_box_for_whitespace: true
    unnecessary_new: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_setters_to_change_properties: false

#    ///false
    overridden_fields: false
